/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unipe.locadora.visao;

/**
 *
 * @author Brauner
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_locacao = new javax.swing.JMenuItem();
        menu_devolucao = new javax.swing.JMenuItem();
        menu_sair = new javax.swing.JMenuItem();
        jMenu_func = new javax.swing.JMenu();
        menu_veiculos = new javax.swing.JMenuItem();
        menu_seguros = new javax.swing.JMenuItem();
        menu_clientes = new javax.swing.JMenuItem();
        menu_funcionarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Locadora de Veiculos - ABC");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brauner\\Desktop\\Java - CCP4\\3 - Estagio\\Projeto Locadora - Rumo Certo\\Imagens\\logo.png")); // NOI18N
        jLabel1.setText("jLabel1");

        painel_principal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel_principalLayout = new javax.swing.GroupLayout(painel_principal);
        painel_principal.setLayout(painel_principalLayout);
        painel_principalLayout.setHorizontalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_principalLayout.createSequentialGroup()
                .addContainerGap(638, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        painel_principalLayout.setVerticalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jMenu1.setText("Operações");

        menu_locacao.setText("Locação");
        menu_locacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_locacaoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_locacao);

        menu_devolucao.setText("Devolução");
        menu_devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_devolucaoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_devolucao);

        menu_sair.setText("Sair");
        menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sairActionPerformed(evt);
            }
        });
        jMenu1.add(menu_sair);

        jMenuBar1.add(jMenu1);

        jMenu_func.setText("Cadastros");

        menu_veiculos.setText("Veículos");
        menu_veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_veiculosActionPerformed(evt);
            }
        });
        jMenu_func.add(menu_veiculos);

        menu_seguros.setText("Seguros");
        menu_seguros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_segurosActionPerformed(evt);
            }
        });
        jMenu_func.add(menu_seguros);

        menu_clientes.setText("Clientes");
        menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_clientesActionPerformed(evt);
            }
        });
        jMenu_func.add(menu_clientes);

        menu_funcionarios.setText("Funcionários");
        menu_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_funcionariosActionPerformed(evt);
            }
        });
        jMenu_func.add(menu_funcionarios);

        jMenuBar1.add(jMenu_func);

        jMenu3.setText("Relatórios");

        jMenuItem4.setText("Rel. de Carros");
        jMenu3.add(jMenuItem4);

        jMenuItem6.setText("Rel. dos Alugueis");
        jMenu3.add(jMenuItem6);

        jMenuItem10.setText("Requisito Especial");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_veiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_veiculosActionPerformed
        
        Veiculos tela = new Veiculos();
        painel_principal.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_menu_veiculosActionPerformed

    private void menu_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_funcionariosActionPerformed
        
        Funcionarios tela = new Funcionarios();
        painel_principal.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_menu_funcionariosActionPerformed

    private void menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_clientesActionPerformed
        
        Clientes tela = new Clientes();
        painel_principal.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_menu_clientesActionPerformed

    private void menu_segurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_segurosActionPerformed
        
        Seguros tela = new Seguros();
        painel_principal.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_menu_segurosActionPerformed

    private void menu_locacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_locacaoActionPerformed
        
        Locacao tela = new Locacao();
        painel_principal.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_menu_locacaoActionPerformed

    private void menu_devolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_devolucaoActionPerformed
        
        Devolucao tela = new Devolucao();
        painel_principal.add(tela);
        tela.setVisible(true);
        
    }//GEN-LAST:event_menu_devolucaoActionPerformed

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenu_func;
    private javax.swing.JMenuItem menu_clientes;
    private javax.swing.JMenuItem menu_devolucao;
    private javax.swing.JMenuItem menu_funcionarios;
    private javax.swing.JMenuItem menu_locacao;
    private javax.swing.JMenuItem menu_sair;
    private javax.swing.JMenuItem menu_seguros;
    private javax.swing.JMenuItem menu_veiculos;
    private javax.swing.JDesktopPane painel_principal;
    // End of variables declaration//GEN-END:variables
}
